[terminal]
shell = { program = "zsh", args = [] }
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11
[window]
dimensions = { columns = 120, lines = 40 }
position = { x = 300, y = 150 }
title = "Terminal by Alacritty"
[selection]
save_to_clipboard = true
